// Pre-bundles the serverless functions Vercel deploys. Vercel compiles api/ files in place
// rather than bundling them, and with package.json "type": "module" Node's ESM resolver
// rejects the extensionless relative specifiers used throughout services/ — so each function
// has to arrive already bundled. npm packages stay external: Vercel's file tracing pulls them
// into the Lambda, and bundling them would break the ones that rely on their own on-disk layout.
//
// Two functions, not one. The Stripe webhook cannot live in the catch-all: Stripe signs the
// raw request bytes, so that route must receive the body unparsed, and it has no Firebase ID
// token to get past the auth gate. Vercel checks the filesystem before applying vercel.json
// rewrites, so api/stripe-webhook.js wins over the `/api/(.*)` rewrite. The Hobby plan's
// 12-function cap leaves plenty of room for the second one.
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const bundles = [
  { entry: ['services', 'vercelApiHandler.ts'], out: ['api', 'index.js'] },
  { entry: ['services', 'stripeWebhookHandler.ts'], out: ['api', 'stripe-webhook.js'] },
];

for (const bundle of bundles) {
  const entryPoint = path.join(projectRoot, ...bundle.entry);
  const outfile = path.join(projectRoot, ...bundle.out);
  const sourceLabel = bundle.entry.join('/');
  const outLabel = bundle.out.join('/');

  const result = await build({
    entryPoints: [entryPoint],
    outfile,
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node20',
    packages: 'external',
    banner: {
      js: '// GENERATED by scripts/buildApiFunction.mjs — do not edit.\n'
        + '// Source: ' + sourceLabel + '. Rebuild with `npm run build:api`.',
    },
    metafile: true,
  });

  const bytes = result.metafile.outputs[path.relative(process.cwd(), outfile).replaceAll('\\', '/')]?.bytes;
  console.log(`${outLabel} bundled${bytes ? ` (${(bytes / 1024).toFixed(1)} kb)` : ''}`);
}
