// GENERATED by scripts/buildApiFunction.mjs — do not edit.
// Source: services/stripeWebhookHandler.ts. Rebuild with `npm run build:api`.

// services/billing/pricing.ts
var SIGNUP_GRANT_TOKENS = 100;
var TOKEN_PACKS = [
  { id: "pack-100", tokens: 100, priceUsd: 9.99, priceCents: 999 },
  { id: "pack-500", tokens: 500, priceUsd: 25.99, priceCents: 2599 },
  { id: "pack-1000", tokens: 1e3, priceUsd: 49.99, priceCents: 4999 }
];
var getTokenPack = (packId) => TOKEN_PACKS.find((pack) => pack.id === packId);
var FREE_STORAGE_BYTES = 5 * 1024 * 1024 * 1024;

// services/billing/stripeClient.ts
var stripePromise = null;
var isStripeConfigured = () => Boolean(process.env.STRIPE_SECRET_KEY);
var getStripe = async () => {
  if (!isStripeConfigured()) return null;
  stripePromise ||= (async () => {
    const { default: Stripe } = await import("stripe");
    return new Stripe(process.env.STRIPE_SECRET_KEY);
  })();
  return stripePromise;
};

// services/firebase/adminApp.ts
var APP_NAME = "archai-api";
var unwrapQuoted = (raw) => {
  const trimmed = raw.trim();
  if (trimmed.length <= 1 || trimmed.startsWith("{")) return trimmed;
  const first = trimmed[0];
  if ((first === "'" || first === '"') && trimmed.endsWith(first)) return trimmed.slice(1, -1);
  return trimmed;
};
var serviceAccountParseError = null;
var readServiceAccount = () => {
  const raw = process.env.FIREBASE_ADMIN_SA_KEY_JSON;
  if (!raw || !raw.trim()) {
    serviceAccountParseError = "FIREBASE_ADMIN_SA_KEY_JSON is not set.";
    return null;
  }
  try {
    const parsed = JSON.parse(unwrapQuoted(raw));
    serviceAccountParseError = null;
    return parsed;
  } catch (error) {
    serviceAccountParseError = `FIREBASE_ADMIN_SA_KEY_JSON is not valid JSON (${error?.message}). This usually means the \\n escapes inside private_key were converted to real line breaks.`;
    console.error(serviceAccountParseError);
    return null;
  }
};
var resolveProjectId = () => process.env.FIREBASE_PROJECT_ID || process.env.VITE_FIREBASE_PROJECT_ID || process.env.GOOGLE_CLOUD_PROJECT || readServiceAccount()?.project_id || "";
var resolveStorageBucket = () => process.env.FIREBASE_STORAGE_BUCKET || process.env.VITE_FIREBASE_STORAGE_BUCKET || (resolveProjectId() ? `${resolveProjectId()}.appspot.com` : "");
var hasAdminCredentials = () => readServiceAccount() !== null;
var appPromise = null;
var getAdminApp = async () => {
  if (appPromise) return appPromise;
  const projectId = resolveProjectId();
  const serviceAccount = readServiceAccount();
  if (!projectId && !serviceAccount) return null;
  appPromise = (async () => {
    const { cert, getApps, initializeApp } = await import("firebase-admin/app");
    const existing = getApps().find((app) => app.name === APP_NAME);
    if (existing) return existing;
    const options = { projectId };
    if (serviceAccount) options.credential = cert(serviceAccount);
    const bucket = resolveStorageBucket();
    if (bucket) options.storageBucket = bucket;
    return initializeApp(options, APP_NAME);
  })();
  appPromise.catch(() => {
    appPromise = null;
  });
  return appPromise;
};
var getAdminFirestore = async () => {
  if (!hasAdminCredentials()) return null;
  const app = await getAdminApp();
  if (!app) return null;
  const { getFirestore } = await import("firebase-admin/firestore");
  return getFirestore(app);
};

// services/billing/tokenLedger.ts
var entitlementRef = (db, uid) => db.collection("entitlements").doc(uid);
var ledgerRef = (db, uid, entryId) => entitlementRef(db, uid).collection("ledger").doc(entryId);
var DEFAULT_ENTITLEMENT = () => ({
  tokenBalance: SIGNUP_GRANT_TOKENS,
  tokensGrantedLifetime: SIGNUP_GRANT_TOKENS,
  tokensSpentLifetime: 0,
  storageBytesUsed: 0,
  storageQuotaBytes: FREE_STORAGE_BYTES
});
var BILLING_UNCONFIGURED_MESSAGE = "Billing is not configured on the server. Set FIREBASE_ADMIN_SA_KEY_JSON (or ALLOW_UNMETERED_API=1 to run without metering).";
var toEntitlement = (data) => ({
  tokenBalance: Number(data?.tokenBalance ?? 0),
  tokensGrantedLifetime: Number(data?.tokensGrantedLifetime ?? 0),
  tokensSpentLifetime: Number(data?.tokensSpentLifetime ?? 0),
  storageBytesUsed: Number(data?.storageBytesUsed ?? 0),
  storageQuotaBytes: Number(data?.storageQuotaBytes ?? FREE_STORAGE_BYTES),
  signupGrantedAt: data?.signupGrantedAt ?? null
});
var creditTokens = async (uid, options) => {
  const { amount, requestId, detail } = options;
  const db = await getAdminFirestore();
  if (!db) throw new Error(BILLING_UNCONFIGURED_MESSAGE);
  const { FieldValue } = await import("firebase-admin/firestore");
  const ref = entitlementRef(db, uid);
  const entry = ledgerRef(db, uid, requestId);
  return db.runTransaction(async (tx) => {
    const [snap, entrySnap] = await Promise.all([tx.get(ref), tx.get(entry)]);
    const existing = snap.exists ? toEntitlement(snap.data()) : { ...DEFAULT_ENTITLEMENT(), signupGrantedAt: null };
    if (entrySnap.exists) return existing.tokenBalance;
    const balanceAfter = existing.tokenBalance + amount;
    tx.set(
      ref,
      {
        ...snap.exists ? {} : { ...existing, createdAt: FieldValue.serverTimestamp() },
        tokenBalance: balanceAfter,
        tokensGrantedLifetime: existing.tokensGrantedLifetime + amount,
        updatedAt: FieldValue.serverTimestamp()
      },
      { merge: true }
    );
    tx.set(entry, {
      type: "purchase",
      amount,
      reason: "purchase",
      detail,
      balanceAfter,
      createdAt: FieldValue.serverTimestamp()
    });
    return balanceAfter;
  });
};

// services/billing/stripeWebhook.ts
var handleStripeWebhook = async (rawBody, signature) => {
  const secret = process.env.STRIPE_WEBHOOK_SECRET;
  if (!secret) {
    return { status: 503, body: { error: "STRIPE_WEBHOOK_SECRET is not configured." } };
  }
  if (!signature) {
    return { status: 400, body: { error: "Missing stripe-signature header." } };
  }
  const stripe = await getStripe();
  if (!stripe) {
    return { status: 503, body: { error: "STRIPE_SECRET_KEY is not configured." } };
  }
  let event;
  try {
    event = stripe.webhooks.constructEvent(rawBody, signature, secret);
  } catch (error) {
    return { status: 400, body: { error: `Signature verification failed: ${error?.message}` } };
  }
  if (event.type !== "checkout.session.completed") {
    return { status: 200, body: { received: true, ignored: event.type } };
  }
  const session = event.data.object;
  if (session.payment_status !== "paid") {
    return { status: 200, body: { received: true, ignored: "unpaid session" } };
  }
  const uid = session.metadata?.uid || session.client_reference_id;
  const packId = session.metadata?.packId;
  if (!uid || !packId) {
    console.error("Stripe session without uid/packId metadata:", session.id);
    return { status: 200, body: { received: true, ignored: "missing metadata" } };
  }
  const pack = getTokenPack(packId);
  if (!pack) {
    console.error("Stripe session for unknown pack:", packId);
    return { status: 200, body: { received: true, ignored: "unknown pack" } };
  }
  const balance = await creditTokens(uid, {
    amount: pack.tokens,
    requestId: `stripe-${event.id}`,
    detail: `Purchased ${pack.tokens.toLocaleString()} tokens ($${pack.priceUsd})`
  });
  return { status: 200, body: { received: true, credited: pack.tokens, balance } };
};

// services/stripeWebhookHandler.ts
var config = { api: { bodyParser: false } };
var readRawBody = (req) => new Promise((resolve, reject) => {
  const chunks = [];
  req.on("data", (chunk) => chunks.push(Buffer.from(chunk)));
  req.on("end", () => resolve(Buffer.concat(chunks)));
  req.on("error", reject);
});
async function handler(req, res) {
  if (req.method !== "POST") {
    res.status(405).json({ error: "Method not allowed" });
    return;
  }
  try {
    const rawBody = await readRawBody(req);
    const signature = req.headers["stripe-signature"];
    const result = await handleStripeWebhook(
      rawBody,
      Array.isArray(signature) ? signature[0] : signature
    );
    res.status(result.status).json(result.body);
  } catch (error) {
    console.error("Stripe webhook failed:", error);
    res.status(500).json({ error: error?.message || String(error) });
  }
}
export {
  config,
  handler as default
};
